CREATE TABLE IF NOT EXISTS mensagens_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Recomendado para identificador único
    membro TEXT NOT NULL,
    data_hora TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Sao_Paulo'),
    mensagem TEXT,
    processada BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS previsoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem_id BIGINT NOT NULL
        REFERENCES mensagens_raw(id),
    mensagem TEXT,
    autor_real TEXT NOT NULL,
    autor_predito TEXT NOT NULL,
    probabilidade REAL NOT NULL,
    categoria TEXT,
    features JSONB,
    status_bot TEXT NOT NULL DEFAULT 'PENDENTE',
    processado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (mensagem_id)
);

CREATE TABLE IF NOT EXISTS mensagens_bot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previsao_id BIGINT NOT NULL
        REFERENCES previsoes(id)
        UNIQUE,
    categoria TEXT NOT NULL,
    personalidade TEXT NOT NULL,
    texto TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDENTE_ENVIO',
    gerado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    enviado_em TIMESTAMPTZ
);